solver: "mcm_all_visit" # [value_iteration, policy_iteration, mcm_first_visit, mcm_all_visit]
discount_factor: 1
state_dim: 100
convergenc_criteria: 0.01
plot_value_space: True
plot_policy_space: True
env_episodes: 1000
epsilon_greedy: 0.15